.github/workflows/publish.yml

Signed-off-by: thaisdeboisfosse <thais.de-boisfosse@owkin.com>

ci: publish on the public PyPi

---

benchmark/camelyon/README.md

Signed-off-by: thaisdeboisfosse <thais.de-boisfosse@owkin.com>

doc: remove parallel install

---

CHANGELOG.md
tests/test_model_loading.py
tests/utils.py

This field is being deprecated
See main PR:https://github.com/Substra/substra/pull/288
Not sure if this needs a changelog entry since it only impacts test util, not user-facing feature. Let me know.

feat: remove Model.category

---

CHANGELOG.md
benchmark/camelyon/weldon_fedavg.py
substrafl/algorithms/pytorch/torch_base_algo.py
substrafl/algorithms/pytorch/torch_fed_avg_algo.py
substrafl/algorithms/pytorch/torch_newton_raphson_algo.py
tests/algorithms/pytorch/test_base_algo.py
tests/algorithms/pytorch/test_newton_raphson.py
tests/conftest.py

feat: remove return from predict and _local_predict

---

README.md

Signed-off-by: Romain Goussault <romain.goussault@owkin.com>

docs: update doc URL and Slack URL in README

---

docs/conf.py
tests/test_model_loading.py

Signed-off-by: Louis Hulot <louis.hulot@owkin.com>

test: fix test model loading

---

CHANGELOG.md
benchmark/camelyon/pure_substrafl/assets/Dockerfile
benchmark/camelyon/pure_substrafl/assets/metric.py
docs/conf.py
substrafl/nodes/test_data_node.py
substrafl/remote/register/register.py
substrafl/remote/substratools_methods.py
tests/assets_factory.py

Companion PR:
- MAIN: https://github.com/Substra/substra-tools/pull/63
- https://github.com/Substra/substra/pull/303
- https://github.com/Substra/substrafl/pull/34
- https://github.com/Substra/substra-documentation/pull/201
- https://github.com/Substra/substra-tests/pull/224

feat: algo to function in substratools

---

tests/assets_factory.py

fix: substratools image

---

CHANGELOG.md
substrafl/remote/register/register.py

chore: local dependencies install in single command

---

CHANGELOG.md
substrafl/dependency.py
substrafl/remote/register/register.py
tests/dependency/test_dependency.py

https://app.asana.com/0/1190766234519625/1202828693058876/f

fix: install current package as local dependency

---

CHANGELOG.md
benchmark/camelyon/pure_substrafl/assets/metric.py
substrafl/model_loading.py
substrafl/remote/register/register.py
substrafl/remote/substratools_methods.py
tests/assets_factory.py

- https://github.com/Substra/substra-tools/pull/65 (MAIN)
- https://github.com/Substra/substra/pull/310
- https://github.com/Substra/substrafl/pull/37
- https://github.com/Substra/substra-documentation/pull/202
- https://github.com/Substra/substra-tests/pull/225

chore: register substratools function with decorator

---

CHANGELOG.md
docs/api/model_loading.rst

doc: model loading page

---

.github/workflows/main-check.yml
CHANGELOG.md

Tested on https://github.com/Substra/substrafl/actions/runs/3435148312
https://github.com/actions/runner-images/issues/2840#issuecomment-790492173

fix: free disk place in ci

---

CHANGELOG.md
substrafl/remote/remote_struct.py

fix: python 3.10 compatibility

---

.github/workflows/main-check.yml
.github/workflows/validate-pr.yml
CHANGELOG.md
benchmark/camelyon/README.md
benchmark/camelyon/pure_substrafl/assets/Dockerfile
setup.py
substrafl/remote/register/register.py
tests/assets_factory.py

- https://github.com/Substra/substra/pull/316
- https://github.com/Substra/substra-tools/pull/68
- https://github.com/Substra/substra-documentation/pull/222
- https://github.com/Substra/substra-tests/pull/230
Use new substratools Docker images using last Ubuntu LTS (22.04) and test on python 3.10.

feat: add python 3.10 support

---

.github/workflows/main-check.yml
.github/workflows/publish.yml
.github/workflows/validate-pr.yml
CHANGELOG.md
docker/substrafl-tests/Dockerfile
setup.py

chore: Github action runs on ubuntu 22.04

---

CHANGELOG.md
README.md
substrafl/exceptions.py
substrafl/remote/register/__init__.py
substrafl/remote/register/register.py
substrafl/remote/substratools_methods.py
tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_newton_raphson.py
tests/algorithms/pytorch/test_one_organization.py
tests/algorithms/pytorch/test_scaffold.py
tests/assets_factory.py
tests/conftest.py
tests/remote/register/test_register.py

- https://github.com/Substra/substra-documentation/pull/214
Asana card: https://app.asana.com/0/1203124674173179/1202555728554939/f

feat: register metric function to wrap metric registration

---

Makefile

fix: set latest substratools for make test-ci

---

CHANGELOG.md
docker/substrafl-tests/Dockerfile

- https://github.com/Substra/substra-tests/pull/232
- https://github.com/owkin/substra-ci/pull/89
- https://github.com/Substra/substrafl/pull/56
- https://github.com/owkin/substra-ci/actions/runs/3534248205

feat: python 3.10

---

substrafl/dependency.py
substrafl/remote/register/generate_wheel.py
tests/dependency/poetry_installable_library/pyproject.toml
tests/remote/register/test_generate_package.py

docs: remove Owkin mention in code

---

.github/workflows/main-check.yml
.github/workflows/validate-pr.yml
benchmark/camelyon/requirements.txt
docker/substrafl-tests/Dockerfile
substrafl/remote/register/register.py

fix: install of libs in order not to over-install them on dependencies

---

.github/workflows/main-check.yml
.github/workflows/windows-subprocess-check.yml
CHANGELOG.md
benchmark/camelyon/benchmarks.py
tests/conftest.py
tests/index_generator/test_np_index_generator.py

test: add subprocess tests on Windows Github Actions

---

CHANGELOG.md
setup.py

fix: remove numpy 1.24

---

.github/workflows/main-check.yml
setup.py

fix: remove numpy 1.24 from setup.py

---

CHANGELOG.md

Signed-off-by: Milouu <milan.roustan@owkin.com>
Remove some artifacts left over from precedent rebase

fix: remove left over artifacts from rebase

---

.github/workflows/main-check.yml

fix: leftover in main check

---

.github/CODEOWNERS

chore: change code owners

---

substrafl/nodes/test_data_node.py

chore: add type check for metric keys in test data node

---

CHANGELOG.md
substrafl/evaluation_strategy.py
substrafl/experiment.py
substrafl/nodes/aggregation_node.py
substrafl/nodes/train_data_node.py
substrafl/strategies/fed_avg.py
substrafl/strategies/newton_raphson.py
substrafl/strategies/scaffold.py
substrafl/strategies/single_organization.py
substrafl/strategies/strategy.py
tests/algorithms/pytorch/test_base_algo.py
tests/conftest.py
tests/strategies/test_fed_avg.py
tests/strategies/test_newton_raphson.py
tests/strategies/test_scaffold.py
tests/strategies/test_single_organization.py

feat: test on any org

---

CHANGELOG.md
substrafl/experiment.py
substrafl/model_loading.py
substrafl/nodes/aggregation_node.py
substrafl/nodes/node.py
substrafl/nodes/test_data_node.py
substrafl/nodes/train_data_node.py
substrafl/strategies/fed_avg.py
substrafl/strategies/newton_raphson.py
substrafl/strategies/scaffold.py
substrafl/strategies/single_organization.py
tests/dependency/test_dependency.py
tests/dependency/test_local_dependencies_file_notebook.ipynb
tests/strategies/test_fed_avg.py
tests/strategies/test_newton_raphson.py
tests/strategies/test_scaffold.py
tests/strategies/test_single_organization.py
tests/test_experiment.py
tests/test_model_loading.py

https://app.asana.com/0/1203124674173179/1203842723899063/f
- https://github.com/Substra/substra-tests/pull/239
- https://github.com/Substra/substra/pull/337
- https://github.com/Substra/substrafl/pull/79
- https://github.com/owkin/substra-ci/actions/runs/4044324704

chore!: rename tuples to tasks

---

benchmark/camelyon/common/data_managers.py
benchmark/camelyon/pure_torch/strategies.py
benchmark/camelyon/weldon_fedavg.py
substrafl/algorithms/pytorch/torch_base_algo.py
substrafl/algorithms/pytorch/torch_newton_raphson_algo.py
substrafl/algorithms/pytorch/torch_scaffold_algo.py
substrafl/algorithms/pytorch/weight_manager.py
substrafl/remote/register/generate_wheel.py
substrafl/strategies/fed_avg.py
substrafl/strategies/newton_raphson.py
substrafl/strategies/scaffold.py
substrafl/strategies/single_organization.py
tests/algorithms/pytorch/test_base_algo.py
tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_newton_raphson.py
tests/algorithms/pytorch/test_scaffold.py
tests/conftest.py
tests/index_generator/test_np_index_generator.py
tests/remote/register/test_register.py
tests/settings.py
tests/strategies/test_fed_avg.py
tests/test_model_loading.py
tests/utils.py

chore: apply new black format

---

substrafl/remote/register/register.py

fix: flake8-bugbear upgrade

---

README.md
setup.py

Goal better pypi page: https://pypi.org/project/substrafl/0.30.2/

docs: update setup.py description

---

CHANGELOG.md
benchmark/camelyon/workflows.py
substrafl/evaluation_strategy.py
tests/algorithms/pytorch/test_base_algo.py
tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_newton_raphson.py
tests/algorithms/pytorch/test_one_organization.py
tests/algorithms/pytorch/test_scaffold.py
tests/test_evaluation_strategy.py

- https://github.com/Substra/substra/issues/343

chore!: default value to None for eval_frequency

---

CHANGELOG.md
benchmark/camelyon/benchmarks.py
benchmark/camelyon/workflows.py
substrafl/dependency.py
substrafl/remote/register/register.py
substrafl/remote/remote_struct.py
tests/dependency/test_dependency.py

fix!: local code stop use the algo class path

---

docs/api/nodes.rst
docs/api/remote.rst
docs/index.rst
substrafl/nodes/test_data_node.py
substrafl/remote/register/register.py

- https://github.com/Substra/substrafl/issues/100

doc: correct TestDataNode docstring

---

CHANGELOG.md
benchmark/camelyon/common/weldon.py
examples/template/template.py
substrafl/nodes/test_data_node.py
substrafl/nodes/train_data_node.py
substrafl/strategies/fed_avg.py
substrafl/strategies/newton_raphson.py
substrafl/strategies/scaffold.py
substrafl/strategies/single_organization.py
substrafl/strategies/strategy.py
tests/strategies/test_scaffold.py

https://github.com/Substra/substrafl/issues/103 + applying https://peps.python.org/pep-3135/

fix: scaffold arguments pass to remote struct

---

substrafl/remote/register/register.py

Fix following https://github.com/Substra/substrafl/pull/110

Fix: fix docker build 

---

CHANGELOG.md
substrafl/model_loading.py
substrafl/nodes/train_data_node.py
substrafl/strategies/fed_avg.py
substrafl/strategies/fed_pca.py
substrafl/strategies/newton_raphson.py
substrafl/strategies/scaffold.py
substrafl/strategies/single_organization.py
substrafl/strategies/strategy.py
tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_scaffold.py
tests/dependency/test_dependency.py
tests/dependency/test_local_dependencies_file_notebook.ipynb
tests/utils.py

Remove old "composite" references that became obsolete after generic task.

chore: remove composite references

---

CHANGELOG.md
substrafl/algorithms/pytorch/weight_manager.py
substrafl/experiment.py
substrafl/model_loading.py
substrafl/nodes/aggregation_node.py
substrafl/nodes/test_data_node.py
substrafl/nodes/train_data_node.py
substrafl/remote/decorators.py
substrafl/remote/register/generate_wheel.py
substrafl/remote/register/register.py
substrafl/strategies/fed_avg.py
substrafl/strategies/fed_pca.py
substrafl/strategies/newton_raphson.py
substrafl/strategies/scaffold.py
substrafl/strategies/single_organization.py
substrafl/strategies/strategy.py
tests/algorithms/pytorch/test_base_algo.py
tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_scaffold.py
tests/algorithms/pytorch/test_weight_manager.py
tests/remote/register/test_register.py
tests/test_model_loading.py

Enforce kwargs on user facing functions using more than 3 arguments.
Cf https://peps.python.org/pep-3102/ for the implementation details.

feat!: enforce kwargs

---

benchmark/camelyon/pure_substrafl/register_assets.py

https://github.com/Substra/substra/pull/353

fix: adjust benchmarks to use new Client configuration

---

substrafl/remote/register/manage_dependencies.py

fix: Windows-compatible temp dir

---

CHANGELOG.md
substrafl/model_loading.py
tests/algorithms/pytorch/test_fed_avg.py

Rename the functions to merge this one https://github.com/Substra/substrafl/pull/142

chore: rename download functions

---

CHANGELOG.md
setup.py

chore: numpy<1.24 for pickle compatibility

---

docs/api/index.rst

Companion PR to https://github.com/Substra/substra-documentation/pull/330

fix: Change API reference doc title

---

CHANGELOG.md
substrafl/strategies/strategy.py
tests/algorithms/pytorch/test_fed_avg.py

chore: keep the last round task outputs

---

tests/algorithms/pytorch/test_base_algo.py
tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_fed_pca_algo.py
tests/algorithms/pytorch/test_newton_raphson.py
tests/algorithms/pytorch/test_scaffold.py
tests/algorithms/pytorch/test_single_organization.py
tests/conftest.py

test: install torch on cpu only

---

.github/workflows/main-check.yml

feat: add workflow dispatch

---

setup.py

Fixes [pypi readme](https://pypi.org/project/substrafl/).

fix: pypi readme

---

tests/algorithms/pytorch/test_fed_avg.py
tests/algorithms/pytorch/test_fed_pca_algo.py
tests/algorithms/pytorch/test_newton_raphson.py
tests/algorithms/pytorch/test_scaffold.py
tests/algorithms/pytorch/test_single_organization.py

fix: tests on simulate experiment

---

tests/algorithms/pytorch/test_fed_avg.py

fix: rm simulate_experiment test from e2e CI

---

CHANGELOG.md
docs/api/index.rst
docs/api/logger.rst
substrafl/__init__.py
substrafl/logger.py

chore: add documentation and check on logger

---

tests/algorithms/pytorch/test_newton_raphson.py

test: separate tests in two for hessian stability

---

CHANGELOG.md
substrafl/remote/register/register.py
tests/remote/register/test_register.py

chore: switch to python-slim

---

CHANGELOG.md
benchmark/camelyon/README.md
benchmark/camelyon/benchmarks.py
benchmark/camelyon/common/utils.py
benchmark/camelyon/workflows.py

https://github.com/owkin/substra-ci/pull/150
Closes FL-1500

chore(benchmark/camelyon): add new cli arguments

---

.github/workflows/main-check.yml
.github/workflows/validate-pr.yml
.github/workflows/windows-subprocess-check.yml
Makefile

chore: remove references to USE_LATEST_SUBSTRATOOLS

---

benchmark/camelyon/pure_substrafl/register_assets.py
changes/202.changed
examples/template/template.py
tests/assets_factory.py

- https://github.com/Substra/substra/pull/405 (main)
- https://github.com/Substra/substra-documentation/pull/412
- https://github.com/Substra/substrafl/pull/202
- https://github.com/Substra/substra-backend/pull/860
- https://github.com/Substra/substra-tests/pull/337
- https://github.com/Substra/orchestrator/pull/394

chore: remove type in DatasetSpec

---

.github/workflows/publish.yml

chore: publish on pypi with hatch

---

.github/workflows/windows-subprocess-check.yml

chore: fix windows tests

---

.github/workflows/main-check.yml
.github/workflows/publish.yml
.github/workflows/validate-pr.yml
.github/workflows/windows-subprocess-check.yml

chore: bump actions using node 16 to node 20

---

changes/213.changed
substrafl/remote/register/register.py
tests/remote/register/test_register.py

chore: run apt update on docker user images

---

benchmark/camelyon/common/utils.py

chore: cancel cp to bool

---

benchmark/camelyon/workflows.py

chore(benchmark): don't wait if the cp is canceled

---

changes/231.fixed
tests/algorithms/pytorch/test_base_algo.py
tests/conftest.py

chore: bump NumPy

---

.github/workflows/towncrier-changelog.yml

- https://github.com/Substra/substra-gha-workflows/pull/24

feat: towncrier reusable workflow

---

changes/242.changed
substrafl/remote/register/register.py

chore: remove CVE cuda image

---

.github/workflows/main-check.yml
.github/workflows/validate-pr.yml
.github/workflows/windows-subprocess-check.yml
changes/247.removed
pyproject.toml
substrafl/dependency/path_management.py
substrafl/remote/register/register.py
tests/installable_library/setup.py
tests/remote/register/test_register.py

chore: drop Python 3.9 support

---

benchmark/camelyon/requirements.txt

chore: bump dependencies for camelyon benchmark

---

.github/workflows/main-check.yml

fix: tests are run on the right python version
