Substra/substrafl

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/main-check.yml, .github/workflows/validate-pr.yml, benchmark/camelyon/common/data_managers.py, benchmark/camelyon/pure_substrafl/assets/Dockerfile, docker/substrafl-tests/Dockerfile, substrafl/remote/register/generate_wheel.py, substrafl/remote/register/register.py, tests/assets_factory.py, tests/remote/register/test_generate_package.py
We decided to use the latest substra-tools image for the test starting from now as we already use it for:
- the benchmark 
- the metric 
Substratools is now installed from the répo and not pypi
Some small updates so the test passes
=> fix: substrafl CI

skaffold.yaml
On all the other repos we now use `substra` as the repository name.
=> ci: update artifact name in skaffold file

skaffold.yaml
Substra tests are now deployed in the `substra-tests` namespace.
=> ci: deploy the tests in the correct namespace

.github/workflows/main-check.yml, .github/workflows/validate-pr.yml, CHANGELOG.md, benchmark/camelyon/.gitattributes, benchmark/camelyon/.gitignore, benchmark/camelyon/README.md, benchmark/camelyon/benchmarks.py, benchmark/camelyon/common/dataset_manager.py, benchmark/camelyon/data/index.csv, benchmark/camelyon/data/tiles_0.5mpp/.gitignore
Stop using Git LFS to store the benchmark data
Out of scope: cache the data to make the benchmark faster, will definitely have to do that, but at least let's fix it first
=> feat(benchmark): use the data hosted on Zenodo

CHANGELOG.md, setup.py, substrafl/algorithms/pytorch/__init__.py, substrafl/exceptions.py
Signed-off-by: Fabien Gelus <fabien.gelus@owkin.com>
Context and user need:
There is a regression bug in torch, that impacts optimizers that have been pickled and unpickled. So this bug appear when using connect for example. This bug occurs for Adam optimizer for example (but not for SGD). Here is a link to one issue covering it:
https://github.com/pytorch/pytorch/pull/80345
present on torch 1.12.0
Functional spec:  it is OK to not support torch 1.12.0, so we can ban it from our supported versions
our examples/benchmark/tests should not use torch 1.12.0
Technical spec:  
Acceptance criteria: user gets an error if they try to use Connectlib with torch 1.12.0
=> fix: throw an error if pytorch 1.12.0 is used

CHANGELOG.md, substrafl/experiment.py, substrafl/nodes/aggregation_node.py, substrafl/nodes/test_data_node.py, substrafl/nodes/train_data_node.py, substrafl/strategies/fed_avg.py, substrafl/strategies/newton_raphson.py, substrafl/strategies/scaffold.py, substrafl/strategies/single_organization.py, substrafl/strategies/strategy.py, tests/algorithms/pytorch/test_base_algo.py, tests/conftest.py, tests/strategies/test_newton_raphson.py
Use the `transient` flag on tasks outputs instead of `clean_models`. This required moving some of the logic responsible for handling transient outputs to the Strategies but it should not impact the user experience since we still handle the feature through the `clean_models` argument of the experiment.
I hardcoded the `transient` property for predict and test tuples since performances cannot be transient and predictions are kind of an useless artifact as far as I know but let me know if the prediction output should be handled through the same argument as for training operations.
=> feat: use transient outputs instead of the clean_models flag

docs/api/strategies.rst
Signed-off-by: Romain Goussault <romain.goussault@owkin.com>
Fix a typo: missing a "d" in federated averaging in the API ref documentation --> https://docs.substra.org/en/latest/substrafl_doc/api/strategies.html#federate-averaging
=> docs: fix typo

CHANGELOG.md, Makefile, benchmark/camelyon/README.md, benchmark/camelyon/pure_substrafl/register_assets.py, examples/template/template.py, pyproject.toml, tests/conftest.py, tests/dependency/test_local_dependencies_file_notebook.ipynb, tests/remote/register/test_register.py, tests/settings.py, tests/test_model_loading.py
https://github.com/Substra/substra/pull/287
https://github.com/Substra/substrafl/pull/19
https://github.com/Substra/substra-tests/pull/210
Tests: only changed `--local` to `--subprocess`
Nothing changed on the test commands in this PR, out of scope
What is used until now:
- main branch checks: `make test-local-slow`
- PR branch checks: `benchmark-local`, `test-subprocess-fast`
- e2e tests: `test-ci`
- benchmark: `benchmark`
Markers:
```python
"slow", # mark test as slow.
"substra", # mark test as using substra.
"docker_only", # mark test as only useful in remote and local docker mode
"e2e", # test run in the end-to-end tests with Substra
"gpu", # gpu tests, to run manually
```
how long each test runs in the CI:
- main branch checks: 18min
- PR checks (tests, not the benchmark):  3-4min …
=> test: update the tests, Client(execution_mode)

CHANGELOG.md, benchmark/camelyon/pure_substrafl/assets/metric.py, tests/assets_factory.py
https://github.com/Substra/substra-tools/pull/60
=> feat: update following the metric change in substratools

.github/workflows/validate-pr.yml, benchmark/camelyon/benchmarks.py, benchmark/camelyon/common/utils.py
benchmark ci at each PR is 5 min, make that shorter by caching the data
from 3 min (or more, the download took 11min once, I don't get why) to 1min30 when the cache is used
=> ci: cache the benchmark data

CHANGELOG.md, benchmark/camelyon/pure_substrafl/register_assets.py, docs/conf.py, substrafl/nodes/aggregation_node.py, substrafl/nodes/test_data_node.py, substrafl/nodes/train_data_node.py, substrafl/remote/register/register.py, tests/assets_factory.py, tests/dependency/test_dependency.py, tests/remote/register/test_register.py
Signed-off-by: Louis Hulot <louis.hulot@owkin.com>
substra-tests: https://github.com/Substra/substra-tests/pull/219 
substrafl: https://github.com/Substra/substrafl/pull/29 (here)
substra: https://github.com/Substra/substra/pull/294 (main)
documentation: https://github.com/Substra/substra-documentation/pull/186
orchestrator: https://github.com/Substra/orchestrator/pull/42
backend: https://github.com/Substra/substra-backend/pull/487 
=> remove: algo category from schemas and models

CHANGELOG.md, substrafl/algorithms/algo.py, substrafl/algorithms/pytorch/torch_base_algo.py
The doctstrings of the Algo base class and TorchAlgo base class were not up to date.
=> doc: update predict algo docstrings

CHANGELOG.md, docs/conf.py, substrafl/exceptions.py, substrafl/experiment.py, substrafl/model_loading.py, substrafl/nodes/aggregation_node.py, substrafl/nodes/test_data_node.py, substrafl/nodes/train_data_node.py, substrafl/remote/substratools_methods.py, tests/algorithms/pytorch/test_base_algo.py, tests/algorithms/pytorch/test_fed_avg.py, tests/algorithms/pytorch/test_one_organization.py, tests/algorithms/pytorch/test_scaffold.py, tests/dependency/test_dependency.py, tests/test_model_loading.py, tests/utils.py
https://github.com/Substra/substra/pull/299
Problem: for the model download, we need to identify the "local train tasks" (ie composite traintuples) to download the model from the right task
I added a filter on the tag for that, may find a better way to do this in the future
=> chore: use generic task

CHANGELOG.md, substrafl/algorithms/pytorch/weight_manager.py, tests/algorithms/pytorch/test_weight_manager.py, tests/conftest.py
- added support for LazyBatchNorm**X**d layers
and 
- added tests to properly check that actually `batch_norm_param` is only about the running mean and variance, in all cases we get the batch norm weight and bias
torch `model.parameters()` iterates on all the parameters of the model
function used in substrafl to get the parameters:
```python
def model_parameters(...):
def my_iterator():
for p in model.parameters():
yield p
if with_batch_norm_parameters:
for p in batch_norm_param(model):
yield p
return my_iterator
```
=> fix: get/set parameters with a batch norm layer

.pre-commit-config.yaml, CHANGELOG.md
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Update flake8 repository from the previous one hosted on GitLab to the new one on GitHub.
=> chore: update flake8 repo in pre-commit config

.github/workflows/main-check.yml, CHANGELOG.md, setup.py
=> fix: remove numpy 1.24.0 from requirements due to TypeError: __generator_ctor() with cloudpickle

CHANGELOG.md, benchmark/camelyon/pure_substrafl/register_assets.py, tests/assets_factory.py
- https://github.com/Substra/substra/pull/332 - MAIN
- https://github.com/Substra/substra-backend/pull/551
- https://github.com/Substra/substra-documentation/pull/246
- https://github.com/Substra/substrafl/pull/67
- https://github.com/Substra/substra-tests/pull/235
- https://github.com/Substra/orchestrator/pull/116
https://app.asana.com/0/1202209633046022/1203074394111393/f
=> chore: remove test only from Datasamples

README.md
Adding instructions for running the test suite to the README
I've tried my best to explain the three different modes (subprocess, docker, remote) in a succinct way, but please correct me for any mistakes or inaccuracies.
I've noted that the extra dependencies for `substra-tools` are under `test`, when it's more usual to use `dev` (and `dev` is used for both `substra` and `substrafl` so it's a small discrepancy). Nothing major, but I don't know if we want to do something about it 🤷‍♀️
=> docs: add test instructions to the README

substrafl/algorithms/pytorch/torch_newton_raphson_algo.py, tests/algorithms/pytorch/test_newton_raphson.py
The current implementation of NewtonRaphson is buggy when batch_size = None. Indeed, in this case, the batch_size is set to n_sample. However, in the predict method, a dataloader was called with batch_size=None, which make the dataloader drop the batch dimension, and set a batch size of 1.
Therefore, the shape of the prediction was missing one dimension. For exemple, setting BATCH_SIZE=None in the test `test_pytorch_nr_algo_performance` would result in a fail, as the MAE metric was not accurate in that situation.
Simply erasing the over-writing of the _local_predict solves that issue. Indeed, the parent _local_predict is checking at the IndexGenerator batch_size which is set to n_samples if batch_size = None. There is no need to overwrite it.
- Adding a specific test
- Fixing the bug
- [ …
=> fix: wrong output shape when batch_size is None in NewtonRaphson

CHANGELOG.md, benchmark/camelyon/workflows.py, examples/template/template.py, substrafl/evaluation_strategy.py, tests/algorithms/pytorch/test_base_algo.py, tests/algorithms/pytorch/test_fed_avg.py, tests/algorithms/pytorch/test_newton_raphson.py, tests/algorithms/pytorch/test_one_organization.py, tests/algorithms/pytorch/test_scaffold.py, tests/test_evaluation_strategy.py, tests/test_experiment.py
https://app.asana.com/0/1203124674173179/1203493303699138/f
=> feat!: clarify eval strategy arguments

CHANGELOG.md, benchmark/camelyon/workflows.py, substrafl/algorithms/pytorch/torch_single_organization_algo.py, substrafl/experiment.py, substrafl/schemas.py, substrafl/strategies/fed_avg.py, substrafl/strategies/newton_raphson.py, substrafl/strategies/scaffold.py, substrafl/strategies/single_organization.py, substrafl/strategies/strategy.py, tests/algorithms/pytorch/test_base_algo.py, tests/algorithms/pytorch/test_fed_avg.py, tests/algorithms/pytorch/test_newton_raphson.py, tests/algorithms/pytorch/test_scaffold.py, tests/algorithms/pytorch/test_single_organization.py, tests/conftest.py, tests/strategies/test_fed_avg.py, tests/strategies/test_newton_raphson.py, tests/strategies/test_scaffold.py, tests/strategies/test_single_organization.py, tests/strategies/test_strategy.py, tests/test_experiment.py
This PRs does two things:
- pass the algo as a parameters for each existing strategy. The base class stays as a generics one in order to keep args and kwargs as init parameters, in order to load all paramters in the remote struct when loading the object.
The algo is no longer a parameter for execute experiment.
- rename strategy.predict to strategy.perform_predict in order to avoid the confusion between these two.
- https://github.com/Substra/substra-documentation/pull/287
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203948519453754
=> feat!: remove-algo-from-execute-exp

CHANGELOG.md, substrafl/remote/register/generate_wheel.py, substrafl/remote/register/register.py
Optimising the generated Dockerfiles for faster image builds: layers changing more often should be placed last.
There has been some discussion regarding whether we should install external PyPI dependencies first, or substra / substrafl first. It has been decided that the end user should not be modifying the version of substra(fl) used very often, but might experiment with their other Python dependencies. Hence the final choice of putting subtra(fl) installation first, even if it means slightly slower image builds for developers.
- [ x] The commit message follows the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification
=> fix: slow Docker images build

substrafl/strategies/fed_avg.py, substrafl/strategies/fed_pca.py, substrafl/strategies/newton_raphson.py, substrafl/strategies/scaffold.py, substrafl/strategies/single_organization.py
Context and user need: The function name will be now shown more in the front (workflow + task list), so let's make sure we have proper names, in particular those generated by SubstraFL
Functional spec:  Rename predict task from "Testing with MyAlgo" to "Predicting with MyAlgo"
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204429917468075
=> chore: rename predict task name

tests/utils.py
Fix https://github.com/Substra/substrafl/pull/129 where instead of trying to load model using its key (previously `output.value.key`), we tried to get a model using the output asset key (`output.key`). Fixed by replacing with `output.asset.value`)
Fixes FL-568
=> fix: `download_train_task_models_by_rank`

tests/conftest.py
Launching the tests in subprocess were failing due to the docker client fixture (used only to prune the images).
We remove the fixture and used it as a get function when pruning the docker images only.
=> fix: subprocess tests run without docker running

CHANGELOG.md, substrafl/model_loading.py, substrafl/nodes/aggregation_node.py, substrafl/nodes/node.py, substrafl/nodes/train_data_node.py, substrafl/remote/substratools_methods.py, tests/algorithms/pytorch/test_base_algo.py, tests/remote/test_decorator.py, tests/test_model_loading.py, tests/utils.py
Remove models and model to input and output identifier to put only `shared_state`. This change help to improve the flexibility on workflows. In particular, it unlock the possibility to link train tasks with each other (needde in cyclic strategy for instance).
Fixes FL-1047 
- https://github.com/Substra/substrafl/pull/142 (main)
- https://github.com/Substra/substra/pull/367
- https://github.com/Substra/substra-tools/pull/84
- https://github.com/Substra/substra-tests/pull/261
=> chore: remove models and model from identifiers

CHANGELOG.md, benchmark/camelyon/workflows.py, tests/algorithms/pytorch/test_base_algo.py, tests/algorithms/pytorch/test_fed_avg.py, tests/algorithms/pytorch/test_fed_pca_algo.py, tests/algorithms/pytorch/test_newton_raphson.py, tests/algorithms/pytorch/test_scaffold.py, tests/algorithms/pytorch/test_single_organization.py, tests/dependency/test_dependency.py, tests/dependency/test_local_dependencies_file_notebook.ipynb, tests/settings.py, tests/strategies/test_fed_avg.py, tests/utils.py
- https://github.com/Substra/substra/pull/368
- https://github.com/Substra/substrafl/pull/147
- https://github.com/Substra/substra-tests/pull/263
- https://github.com/Substra/substra-documentation/pull/327
Centralize `wait_task` and `wait_compute_plan`, and re-use the implementation added in `substra` through the other components.
Fixes FL-1052
=> chore: centralize wait task in substrasdk

CHANGELOG.md, substrafl/algorithms/pytorch/torch_base_algo.py, substrafl/algorithms/pytorch/torch_newton_raphson_algo.py
Predictions tensor was not initialised on the right device.
Cause incompatibilty when applying `torch.cat` on it.
Tested with MNIST example on a GPU setup.
closes FL-565
=> fix: gpu usage

tests/dependency/test_dependency.py
=> test: fix test_force_editable_mode

CHANGELOG.md, docs/conf.py, setup.py, substrafl/dependency/schemas.py, substrafl/nodes/aggregation_node.py, substrafl/nodes/test_data_node.py, substrafl/nodes/train_data_node.py
- https://github.com/Substra/substra/pull/375 (main)
- https://github.com/Substra/substrafl/pull/159
- https://github.com/Substra/substra-tests/pull/272
- https://github.com/Substra/substra-backend/pull/718
=> chore: bump pydantic to 2.3.0

substrafl/algorithms/pytorch/torch_base_algo.py
This PR speeds up the inference in `_local_predict`: instead of copying multiple times the array (implied work with `torch.cat`), it stores all outputs in a list (no copy) and then concenates once.
=> chore: refactor _local_predict for better performances

.github/workflows/main-check.yml, .github/workflows/validate-pr.yml, .github/workflows/windows-subprocess-check.yml, CHANGELOG.md, benchmark/camelyon/README.md, benchmark/camelyon/pure_substrafl/register_assets.py, benchmark/camelyon/requirements.txt, benchmark/camelyon/workflows.py, docker/substrafl-tests/Dockerfile, examples/template/template.py, setup.py, substrafl/remote/register/register.py, tests/remote/register/test_register.py
- https://github.com/Substra/substra-tools/pull/85 (main)
- https://github.com/Substra/substrafl/pull/169
- https://github.com/Substra/substra/pull/388
- https://github.com/Substra/substra-tests/pull/283
- https://github.com/Substra/substra-documentation/pull/367
- https://github.com/owkin/substra-ci/pull/127
- https://github.com/owkin/substra-generator/pull/136
closes FL-979
=> chore: add python 3.11 support

CHANGELOG.md, substrafl/dependency/manage_dependencies.py
=> feat: remove substrafl wheel cache

benchmark/camelyon/requirements.txt, benchmark/camelyon/workflows.py, substrafl/dependency/manage_dependencies.py
=> fix: install torch cpu for camelyon benchmark

CHANGELOG.md, benchmark/camelyon/.gitignore, benchmark/camelyon/benchmarks.py, benchmark/camelyon/common/dataset_manager.py
closes FL-1250
Zenodo changed the access management to some of there datasets (for instance to ensure that its access for academic purposes)
We changed our download url to point to a dataset we (owkin) put online -> https://zenodo.org/records/7053167
=> fix(benchmark): download data for camelyon

CHANGELOG.md, substrafl/dependency/schemas.py, substrafl/nodes/train_data_node.py, substrafl/strategies/schemas.py, tests/settings.py
=> chore: remove warnings from pydantic v2

CHANGELOG.md, benchmark/camelyon/data/index.csv, tests/remote/register/test_register.py
=> feat: rename function field of Function to archive

substrafl/model_loading.py, tests/test_model_loading.py
Companion PR  https://github.com/Substra/substra/pull/399
=> chore: rename compute task status

CHANGELOG.md, substrafl/algorithms/pytorch/torch_newton_raphson_algo.py, tests/algorithms/pytorch/test_newton_raphson.py
This PR ensures that the Hessian computed locally in the NewtonRaphson strategy is *numerically* symmetric by computing
```python
hessian = 0.5 * hessian + 0.5 * hessian.T
```
Indeed, floating point errors may make it slightly asymmetric as it is computed by pytorch, resulting in very low eigenvalues. This can be verified by running the introduced test on `main`, which fails without the patch;
The bug was originally spotted by @jeandut ;)
=> fix: improve stability of Newton Raphson by symmetrizing the Hessian

CHANGELOG.md, README.md, changes/201.added, pyproject.toml, setup.py
Add `towncrier` for changelog management. 
Output: 
```
$ towncrier build --version=0.45.0 --draft
Loading template...
Finding news fragments...
Rendering news fragments...
Draft only -- nothing has been written.
What is seen below is what would be written.
- - New CLI arguments to Camelyon benchmark (`--torch-gpu` and `--cp-name`)([#201](https://github.com/Substra/substrafl/pull/201)) (#201)
```
=> chore: set up towncrier for changelog management

benchmark/camelyon/benchmarks.py, benchmark/camelyon/common/utils.py
=> chore: allow skip pure torch computation on benchmark camelyon

Makefile, changes/229.fixed, tests/test_experiment.py
=> fix: mark simulation mode tests as subprocess-only

changes/228.fixed, substrafl/remote/register/register.py, tests/remote/register/test_register.py
=> fix: ensure that compute functions are running as non-root

changes/230.fixed, tests/algorithms/pytorch/test_base_algo.py, tests/conftest.py
Fixes the CI following Python 3.12 support.
=> chore: bump Pytorch version to 2.2.1 in tests

changes/241.changed, substrafl/algorithms/pytorch/torch_base_algo.py, substrafl/algorithms/pytorch/torch_fed_avg_algo.py, substrafl/algorithms/pytorch/torch_fed_pca_algo.py, substrafl/algorithms/pytorch/torch_newton_raphson_algo.py, substrafl/algorithms/pytorch/torch_scaffold_algo.py, substrafl/algorithms/pytorch/torch_single_organization_algo.py, tests/algorithms/pytorch/test_base_algo.py, tests/algorithms/pytorch/test_fed_avg.py, tests/algorithms/pytorch/test_fed_pca_algo.py, tests/algorithms/pytorch/test_newton_raphson.py, tests/algorithms/pytorch/test_scaffold.py, tests/algorithms/pytorch/test_single_organization.py
closes FL-1677
- https://github.com/Substra/substra-documentation/pull/436
-  https://github.com/Substra/substrafl/pull/241
=> chore: rename use_gpu to disable_gpu in TorchAlgo

benchmark/camelyon/benchmarks.py, benchmark/camelyon/common/utils.py, benchmark/camelyon/workflows.py, changes/244.fixed
=> fix(benchmark/camelyon): actually rely on gpu setup at `Dependency` level

benchmark/camelyon/weldon_fedavg.py, changes/245.fixed
```python
Traceback (most recent call last):
File "/home/user/function.py", line 22, in <module>
tools.execute()
File "/home/user/venv/lib/python3.10/site-packages/substratools/function.py", line 236, in execute
args.func(args, function)
File "/home/user/venv/lib/python3.10/site-packages/substratools/function.py", line 193, in _user_func
function_wrapper.execute(
File "/home/user/venv/lib/python3.10/site-packages/substratools/utils.py", line 58, in wrapper
result = func(*args, **kwargs)
File "/home/user/venv/lib/python3.10/site-packages/substratools/function.py", line 156, in execute
function(
File "/home/user/venv/lib/python3.10/site-packages/substrafl/remote/substratools_methods.py", line 113, in generic_function
method_output = method_to_call(
File …
```
=> fix(camelyon/weldon_fedavg): can't convert cuda:0 device type tensor to numpy

changes/250.changed, substrafl/remote/register/register.py, tests/remote/register/test_register.py
=> chore: update setuptools in docker images

changes/248.changed, substrafl/remote/register/register.py, tests/remote/register/test_register.py
=> chore: bump cuda base version to a more recent one

changes/249.added, substrafl/dependency/schemas.py, substrafl/remote/register/register.py, tests/dependency/test_dependency.py, tests/remote/register/test_register.py
=> feat: add the option to inject binary libraries to install in Dockerfile

changes/256.fixed, substrafl/remote/register/register.py, tests/remote/register/test_register.py
Patch to make the generated Dockerfile compatible with kaniko behaviour on AWS
=> fix: docker image template to work on AWS
